version: '{build}'
image: Visual Studio 2019

environment:
  matrix:
  - TARGET: dotnet
  - TARGET: native
    UNO_TEST_ARGS: -DDEBUG_UNSAFE
    SKIP_UNO_TESTS: 1
  # - TARGET: android
  #   UNO_TEST_ARGS: -DDEBUG_UNSAFE --build-only
  #   GRADLE_OPTS: -Dorg.gradle.daemon=false
  #   SKIP_LIB_TESTS: 1

install:
  - ps: |
      if ($env:Target -eq "android") {
        Invoke-Expression "npm install android-build-tools -g"
      }
  - npm install

build_script:
  - npm pack --silent

after_build:
  - ps: |
      if ($env:Target -eq "dotnet") {
        Push-AppveyorArtifact "fuse-open-uno-*.tgz"
      }

before_test:

test_script:
  - nunit3-console
      src\test\tests\bin\Release\Uno.TestRunner.Tests.dll
      src\ux\tests\bin\Release\Uno.UX.Markup.Tests.dll
  - npm test %TARGET%
