# Uncomment this line to define a global platform for your project
#if @(Cocoapods.Platform.Name:isset)
platform :@(Cocoapods.Platform.Name), '@(Cocoapods.Platform.Version || '')'
#endif

@(Cocoapods.Podfile.Pre:join('\n'))

target '@(Project.Name)' do
#if @(Pods.Frameworks:defined)
  use_frameworks!
#endif
  @(Cocoapods.Podfile.Target:join('\n'))
end

@(Cocoapods.Podfile.Post:join('\n'))
